os: linux
language: python
python:
  - "3.6"
virtualenv:
  system_site_packages: false
  user_site_packages: true
install:
  - pip3 install --upgrade pip
  - pip3 install --upgrade coverage
  - pip3 install --upgrade -e ../mlak/
script:
  - ./tests/run.sh
addons:
  apt:
    packages:
      - python3-pip
      - python3-tk

